---
- name: Configure training server
  hosts: training-machine
  remote_user: zansin
  become: yes
  vars:
    hostname: training-machine
    ansible_ssh_user: zansin
    ansible_ssh_pass: Passw0rd!
    ansible_become_password: Passw0rd!
  roles:
    - name: training-machine
      # Add import statement for training-machine role
      import_role:
        name: training-machine

- name: Setup control server
  hosts: zansin-control-server
  remote_user: zansin
  become: yes
  vars:
    hostname: zansin-control-server
    ansible_ssh_user: zansin
    ansible_ssh_pass: Passw0rd!
    ansible_become_password: Passw0rd!
  roles:
    - name: zansin-control-server
      # Add import statement for zansin-control-server role
      import_role:
        name: zansin-control-server
      tags: zansin-control-server
