---
- name: Configure game server
  hosts: all
  become: yes
  remote_user: hardmini
  gather_facts: True

  vars:
    hostname: game-server
    ansible_ssh_private_key_file: ~/.ssh/team.pem
    ansible_ssh_public_key_file: ~/.ssh/team.pub
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  roles:
   - game-server

