#- name: clone front repository
#  become: yes
#  shell: "{{ item }}"
#  with_items:
#    - "git clone https://{{ lookup('env', 'github_user') }}:{{ lookup('env', 'github_pat') }}@github.com/minihardening/mini4-front.git && cd mini4-front && rm -rf .git && sudo cp -rf ./* /var/www/html/"

#- name: clone game-api repository
#  become: yes
#  shell: "{{ item }}"
#  with_items:
#    - "git clone https://{{ lookup('env', 'github_user') }}:{{ lookup('env', 'github_pat') }}@github.com/minihardening/mini4-game-api-php.git && rm -rf mini4-game-api-php/.git && sudo mv mini4-game-api-php /home/vendor/mini4-game-api-php"
#    - "sudo chown -R vendor:vendor /home/vendor && sudo chmod 777 /home/vendor/mini4-game-api-php/public/images/players"

- name: Copy front files
  ansible.builtin.copy:
    src: front/
    dest: /var/www/html/
    remote_src: no

- name: Copy game contents files
  ansible.builtin.copy:
    src: game-api/
    dest: /home/vendor/game-api/
    remote_src: no
    owner: vendor
    group: vendor
    mode: '0755'