
- name: Copy front files
  ansible.builtin.copy:
    src: front/
    dest: /var/www/html/
    remote_src: no

- name: Copy game contents files
  ansible.builtin.copy:
    src: game-api/
    dest: /home/vendor/game-api/
    remote_src: no
    owner: vendor
    group: vendor
    mode: '0755'

- name: Permission settings for the upload directory
  file:
    path: /home/vendor/game-api/public/images/players
    owner: vendor
    group: vendor
    mode: 0777