- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker.io

## Enable specified regular users to use Docker without sudo.
- name: add ubuntu to dcoker group
  shell: "sudo gpasswd -a vendor docker"

# Make it possible for regular users to read the sockets used by Docker.
- name: chmod /var/run/docker.sock
  shell: "sudo chmod 666 /var/run/docker.sock"

- name: copy docker.service
  become: yes
  template:
    src: docker.service
    dest: /lib/systemd/system/docker.service

- name: be sure docker is running and enabled
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'

# Granting Execute Permissions
- name: chmod docker-compose
  shell: "sudo chmod 0755 /usr/local/bin/docker-compose"
