---
# tasks file for team-db
- name: create user
  become: yes
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes
    groups: root
    append: yes
    state: present
    update_password: on_create
  with_items:
  - { name: 'mario', password: 'Passw0rd!23' }
  - { name: 'link', password: 'Passw0rd!23' }
  - { name: 'sonic', password: 'Passw0rd!23' }
  - { name: 'vendor', password: 'Passw0rd!23' }

- name: change sudoers
  become: yes
  template:
    src: 90-cloud-init-users
    dest: /etc/sudoers.d/90-cloud-init-users
    mode: '0440'
